service: spikey-app-service

runtime: python37
instance_class: B8

basic_scaling:
  max_instances: 10
  idle_timeout: 10m
  
handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html

- url: /(.*)
  static_files: www/\1
  upload: www/(.*)
  
  
  
  