
SECRET_KEY = 'secret'


PROJECT_ID = 

CLOUD_STORAGE_BUCKET = 
MAX_CONTENT_LENGTH = 8 * 1024 * 1024
ALLOWED_EXTENSIONS = set(['png', 'jpg', 'jpeg', 'gif'])

# OAuth2 configuration.
GOOGLE_OAUTH2_CLIENT_ID = 
GOOGLE_OAUTH2_CLIENT_SECRET = 
